replicaCount: 2

image:
  repository: 003150130236.dkr.ecr.eu-central-1.amazonaws.com/product/dev
  tag: '922a6cbdfbf1f7e02d570a1b02fd05e7446cf50c'
  pullPolicy: IfNotPresent

service:
  name: dev-app
  targetPort: 8080

ingress:
  name: dev-ingress

loadbalancer:
  name: dev-alb

rollout:
  enabled: false
