replicaCount: 2

image:
  repository: 003150130236.dkr.ecr.eu-central-1.amazonaws.com/product/dev
  tag: '730959c29be40d640004dc66ac23ff45a8145198'
  pullPolicy: IfNotPresent

service:
  name: dev-app
  targetPort: 8080

ingress:
  name: dev-ingress

loadbalancer:
  name: dev-alb

rollout:
  enabled: false
