replicaCount: 2

image:
  repository: 003150130236.dkr.ecr.eu-central-1.amazonaws.com/product/dev
  tag: '6a2ec03a16823c2e13b97716d7ae14c8961dbfaf'
  pullPolicy: IfNotPresent

service:
  name: dev-app
  targetPort: 8080

ingress:
  name: dev-ingress

loadbalancer:
  name: dev-alb

rollout:
  enabled: false
