replicaCount: 2

image:
  repository: 003150130236.dkr.ecr.eu-central-1.amazonaws.com/product/prod
  tag: '9d8a6e5671d4c7c0beef73b8f2e00dbbc74075a2'
  pullPolicy: IfNotPresent

service:
  name: prod-app
  targetPort: 8080

ingress:
  name: prod-ingress
  
loadbalancer:
  name: prod-alb

rollout:
  enabled: true
